component: scf
name: yangmaojb
app: yangmaojb
inputs:
  name: yangmaojb
  src: ./
  description: yangmaojb
  handler: index.main_handler
  runtime: Nodejs12.16
  namespace: default
  region: ap-hongkong 
  memorySize: 128
  timeout: 900
  environment:
    variables:
      RUN_CONFIG: '{"jd_petTreasureBox":{"run":"false"}}'
      FRUIT_NOTIFY_CONTROL: 'true'
      JD_JOY_REWARD_NOTIFY: 'true'
      PET_NOTIFY_CONTROL: 'true'
      JD_IMMORTAL_LATLON: '{"lat":22.8,"lng":108.2}'
      JXNCTOKENS: '{"farm_jstoken":"9a26c3d5fdd1668d91900f473141c32c","timestamp":"1610441576034","phoneid":"bdc03a4fc9be38b2-35355204688244"}'
      JD_WECHAT_USER_AGENT: 'Mozilla/5.0 (Linux; Android 10; COL-AL10 Build/HUAWEICOL-AL10; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/77.0.3865.120 MQQBrowser/6.2 TBS/045230 Mobile Safari/537.36'
  events:
    - timer:
        parameters:
          name: jd_car_exchange_blueCoin
          cronExpression: "0 0,2 0 * * * *"	
          enable: true
          argument: async_jd?jd_blueCoin.js&&jd_car_exchange.js
    - timer:
        parameters:
          name: jd_live_redrain2
          cronExpression: "0 0,1 19-21 * * * *"
          enable: true
          argument: async_jd?jd_live_redrain2.js
    - timer:
        parameters:
          name: jd_live_redrain_half
          cronExpression: "0 30,31 12-23 * * * *"
          enable: true
          argument: async_jd?jd_live_redrain_half.js
    - timer:
        parameters:
          name: jd_live_redrain_nian
          cronExpression: "0 0 0,9-23 3,5,20-30 1,2 * *"
          enable: true
          argument: async_jd?jd_live_redrain_nian.js
    - timer:
        parameters:
          name: jd_live_redrain_offical
          cronExpression: "0 0 0,9-17/2,19-23 * * * *"
          enable: true
          argument: async_jd?jd_live_redrain_offical.js
    - timer:
        parameters:
          name: jd_live
          cronExpression: "0 10,15,20 12 * * * *"
          enable: true
          argument: async_jd?jd_live.js
    - timer:
        parameters:
          name: jd_lotteryMachine
          cronExpression: "0 0 20,22 * * * *"
          enable: true
          argument: async_jd?jd_lotteryMachine.js
    - timer:
        parameters:
          name: jd_immortal
          cronExpression: "0 0 21 * * * *"
          enable: true
          argument: async_jd?jd_immortal.js
    - timer:
        parameters:
          name: noasync
          cronExpression: "0 13,43 * * * * *"
          enable: true
          argument: noasync_jd