component: scf
name: yangmao_Jd
app: yangmao_Jd
stage: dev
inputs:
  name: yangmao_Jd
  src: ./
  description: yangmao_script
  handler: index.main_handler
  runtime: Nodejs12.16
  namespace: default
  region: ap-hongkong 
  memorySize: 64
  timeout: 333
  environment:
    variables:
      QD_TEXT: 天天签到，天天开心
  events:
    - timer:
        parameters:
          name: jd_car_exchange
          cronExpression: "10 0,2 0 * * * *"
          enable: true
          argument: jd_script/jd_car_exchange.js
    - timer:
        parameters:
          name: jd_live_redrain2
          cronExpression: "0 30,31 20-23 * * * *"
          enable: true
          argument: jd_script/jd_live_redrain2.js
    - timer:
        parameters:
          name: jd_nianCollect
          cronExpression: "0 33 * * * * *"
          enable: true
          argument: jd_script/jd_nianCollect.js
