component: scf
name: yangmaojb
app: yangmaojb
inputs:
  name: yangmaojb
  src: ./
  description: yangmaojb
  handler: index.main_handler
  runtime: Nodejs12.16
  namespace: default
  region: ap-hongkong 
  memorySize: 128
  timeout: 900
  environment:
    variables:
      RUN_CONFIG: '{"jd_cash":{"run":"false"}}'
      FRUIT_NOTIFY_CONTROL: 'true'
      JD_JOY_REWARD_NOTIFY: 'true'
      PET_NOTIFY_CONTROL: 'true'
      JXNCTOKENS: '{"farm_jstoken":"9a26c3d5fdd1668d91900f473141c32c","timestamp":"1610441576034","phoneid":"bdc03a4fc9be38b2-35355204688244"}'
      JD_WECHAT_USER_AGENT: 'Mozilla/5.0 (Linux; Android 10; COL-AL10 Build/HUAWEICOL-AL10; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/77.0.3865.120 MQQBrowser/6.2 TBS/045230 Mobile Safari/537.36'
  events:
    - timer:
        parameters:
          name: jd_car_exchange_blueCoin_cash
          cronExpression: "58 59 23 * * * *"
          enable: true
          argument: async_jd?jd_blueCoin.js&&jd_car_exchange.js
    - timer:
        parameters:
          name: jd_car_exchange_blueCoin_cash2
          cronExpression: "58 0 0 * * * *"
          enable: true
          argument: async_jd?jd_blueCoin.js&&jd_car_exchange.js
    - timer:
        parameters:
          name: jd_cash
          cronExpression: "0 21 0-18 * * * *"
          enable: true
          argument: async_jd?jd_cash.js
    - timer:
        parameters:
          name: jd_live
          cronExpression: "0 10,15,20 12 * * * *"
          enable: true
          argument: async_jd?jd_live.js
    - timer:
        parameters:
          name: noasync
          cronExpression: "0 13,43 * * * * *"
          enable: true
          argument: noasync_jd