#定时同步github代码
name: 同步代码并部署到腾讯云
on:
  workflow_dispatch:
  schedule:
    - cron: 0 23 * * *
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: "安装依赖 serverless工具"
        run: |
          npm install
          sudo npm install serverless -g
      - name: "运行下载代码脚本"
        run: |
          node dlcode.js
      - name: commit-push code
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git_status=$(git status)
          if [[ "$git_status" != *"up to date"* ]];then git commit -m "sync code by action"&&git push;fi
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE}}
          JD_USER_AGENT: ${{ secrets.JD_USER_AGENT}}
          JD_BEAN_STOP: ${{ secrets.JD_BEAN_STOP}}
          JD_BEAN_SIGN_STOP_NOTIFY: ${{ secrets.JD_BEAN_SIGN_STOP_NOTIFY}}
          JD_BEAN_SIGN_NOTIFY_SIMPLE: ${{ secrets.JD_BEAN_SIGN_NOTIFY_SIMPLE}}
          PUSH_KEY: ${{ secrets.PUSH_KEY}}
          BARK_PUSH: ${{ secrets.BARK_PUSH}}
          BARK_SOUND: ${{ secrets.BARK_SOUND}}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN}}
          TG_USER_ID: ${{ secrets.TG_USER_ID}}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN}}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET}}
          QYWX_KEY: ${{ secrets.QYWX_KEY}}
          IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY}}
          QQ_SKEY: ${{ secrets.QQ_SKEY}}
          QQ_MODE: ${{ secrets.QQ_MODE}}
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN}}
          PUSH_PLUS_USER: ${{ secrets.PUSH_PLUS_USER}}
          PET_NOTIFY_CONTROL: ${{ secrets.PET_NOTIFY_CONTROL}}
          FRUIT_NOTIFY_CONTROL: ${{ secrets.FRUIT_NOTIFY_CONTROL}}
          JD_JOY_REWARD_NOTIFY: ${{ secrets.JD_JOY_REWARD_NOTIFY}}
          JD_818_SHAREID_NOTIFY: ${{ secrets.JD_818_SHAREID_NOTIFY}}
          JOY_FEED_COUNT: ${{ secrets.JOY_FEED_COUNT}}
          JOY_HELP_FEED: ${{ secrets.JOY_HELP_FEED}}
          JOY_RUN_FLAG: ${{ secrets.JOY_RUN_FLAG}}
          JOY_TEAM_LEVEL: ${{ secrets.JOY_TEAM_LEVEL}}
          JD_JOY_REWARD_NAME: ${{ secrets.JD_JOY_REWARD_NAME}}
          MARKET_COIN_TO_BEANS: ${{ secrets.MARKET_COIN_TO_BEANS}}
          MARKET_REWARD_NOTIFY: ${{ secrets.MARKET_REWARD_NOTIFY}}
          SUPERMARKET_UPGRADE: ${{ secrets.SUPERMARKET_UPGRADE}}
          BUSINESS_CIRCLE_JUMP: ${{ secrets.BUSINESS_CIRCLE_JUMP}}
          SUPERMARKET_LOTTERY: ${{ secrets.SUPERMARKET_LOTTERY}}
          FRUIT_BEAN_CARD: ${{ secrets.FRUIT_BEAN_CARD}}
          UN_SUBSCRIBES: ${{ secrets.UN_SUBSCRIBES}}
          UN_BIND_CARD_NUM: ${{ secrets.UN_BIND_CARD_NUM}}
          UN_BIND_STOP_CARD: ${{ secrets.UN_BIND_STOP_CARD}}
          JDJOY_HELPSELF: ${{ secrets.JDJOY_HELPSELF}}
          JDJOY_APPLYJDBEAN: ${{ secrets.JDJOY_APPLYJDBEAN}}
          FRUITSHARECODES: ${{ secrets.FRUITSHARECODES}}
          PETSHARECODES: ${{ secrets.PETSHARECODES}}
          PLANT_BEAN_SHARECODES: ${{ secrets.PLANT_BEAN_SHARECODES}}
          SUPERMARKET_SHARECODES: ${{ secrets.SUPERMARKET_SHARECODES}}
          DDFACTORY_SHARECODES: ${{ secrets.DDFACTORY_SHARECODES}}
          DREAM_FACTORY_SHARE_CODES: ${{ secrets.DREAM_FACTORY_SHARE_CODES}}
          JDZZ_SHARECODES: ${{ secrets.JDZZ_SHARECODES}}
          JDJOY_SHARECODES: ${{ secrets.JDJOY_SHARECODES}}
          BOOKSHOP_SHARECODES: ${{ secrets.BOOKSHOP_SHARECODES}}
          JXNC_SHARECODES: ${{ secrets.JXNC_SHARECODES}}
          TG_PROXY_HOST: ${{ secrets.TG_PROXY_HOST}}
          TG_PROXY_PORT: ${{ secrets.TG_PROXY_PORT}}
          MONEY_TREE_SELL_FRUIT: ${{ secrets.MONEY_TREE_SELL_FRUIT}}
          FACTORAY_WANTPRODUCT_NAME: ${{ secrets.FACTORAY_WANTPRODUCT_NAME}}
          WATCH_ACCEPTBODY: ${{ secrets.WATCH_ACCEPTBODY}}
          WATCH_DOBODY: ${{ secrets.WATCH_DOBODY}}
          JXNCTOKENS: ${{ secrets.JXNCTOKENS}}
      - name: "部署到腾讯云函数"
        run: serverless deploy
        env:
          STAGE: dev
          SERVERLESS_PLATFORM_VENDOR: tencent
          TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
          TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}